<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Framework
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/**
 * Used to initialize the framework in the various template files.
 *
 * It pulls in all the necessary components like header and footer, the basic
 * markup structure, and hooks.
 *
 * @since 1.3.0
 */
function dg_genesis() {

	get_header();

	if( is_page_template( 'templates/t-about.php' ) ){

		do_action('dg_about_before_content_wrap');

			do_action('dg_about_before_content');

				do_action('dg_about_before_loop');

					do_action('dg_about_loop');

				do_action('dg_about_after_loop');

			do_action('dg_about_after_content');

		do_action('dg_about_after_content_wrap');

	} elseif( is_page_template('templates/t-contact.php') ) {

		do_action('dg_contact_before_content_wrap');

			do_action('dg_contact_before_content');

				do_action('dg_contact_before_loop');

					do_action('dg_contact_loop');

				do_action('dg_contact_after_loop');

			do_action('dg_contact_after_content');

		do_action('dg_contact_after_content_wrap');

	} elseif( is_page_template('darkes-brewing.php') ) {

		do_action('dg_darkes_brewing');

	} elseif( is_page_template('glenbenie-orchard-template.php') ) {

		do_action('dg_glenbenie_orchard');

	} elseif( is_page_template('appleshack-shop-template.php') ) {

		do_action('dg_appleshack');

	} else {
		do_action( 'genesis_before_content_sidebar_wrap' );

		genesis_markup( array(
			'open'   => '<div %s>',
			'context' => 'content-sidebar-wrap',
		) );

			do_action( 'genesis_before_content' );
			genesis_markup( array(
				'open'   => '<main %s>',
				'context' => 'content',
			) );
				do_action( 'genesis_before_loop' );
				do_action( 'genesis_loop' );
				do_action( 'genesis_after_loop' );
			genesis_markup( array(
				'close' => '</main>', // End .content.
				'context' => 'content',
			) );
			do_action( 'genesis_after_content' );

		genesis_markup( array(
			'close'   => '</div>',
			'context' => 'content-sidebar-wrap',
		) );

		do_action( 'genesis_after_content_sidebar_wrap' );
	}

	get_footer();

}
